networks:
  backend:
  frontend:

volumes:
  db-data:
    driver: local

services:
  postgres:
    image: 'postgres:15.1-alpine'
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: ./backend
    env_file: ./backend/.env
    depends_on:
      - postgres
    networks:
      - backend
      - frontend
    environment:
      - HOST=postgres:5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8080:8080'  

  front:
    build:
      context: ./frontend
    networks:
      - frontend
    depends_on:
      - app
    ports:
      - "80:80"
    restart: always

