version: '3.0'

services:
  postgres:
    image: 'postgres:15.1-alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

