/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Physics circuits simulation Engine
 * Sample API of the Physics project engine
 * OpenAPI spec version: 1.0.0
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";
import type {
  ElectricalComponentDto,
  GetUserResponse,
  GetUsersPermissionsResponse,
  JwtResponse,
  SchemeCreateRequest,
  SchemeResponse,
  SetPermissionsRequest,
  SignInRequest,
  SignUpAdminRequest,
  SignUpRequest,
} from "./index.schemas";

export const getSchemeById = <TData = AxiosResponse<SchemeResponse>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/schemes/${id}`, options);
};

export const updateScheme = <TData = AxiosResponse<string>>(
  id: number,
  electricalComponentDto: ElectricalComponentDto[],
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(`/api/schemes/${id}`, electricalComponentDto, options);
};

export const setPermissionsByIdScheme = <TData = AxiosResponse<string>>(
  id: number,
  setPermissionsRequest: SetPermissionsRequest[],
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(`/api/schemes/${id}/permissions`, setPermissionsRequest, options);
};

export const deletePermissionsByIdScheme = <TData = AxiosResponse<string>>(
  id: number,
  setPermissionsRequest: SetPermissionsRequest[],
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(`/api/schemes/${id}/permissions`, { data: setPermissionsRequest, ...options });
};

export const getAllSchemes = <TData = AxiosResponse<SchemeResponse[]>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/schemes`, options);
};

export const createNewScheme = <TData = AxiosResponse<SchemeResponse>>(
  schemeCreateRequest: SchemeCreateRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/schemes`, schemeCreateRequest, options);
};

/**
 * Registers a new user with provided details and generates JWT token
 * @summary User registration
 */
export const register = <TData = AxiosResponse<JwtResponse>>(
  signUpRequest: SignUpRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/auth/register`, signUpRequest, options);
};

/**
 * Registers a new administrator with provided details and admin key, and generates JWT token
 * @summary Admin registration
 */
export const registerAdmin = <TData = AxiosResponse<JwtResponse>>(
  signUpAdminRequest: SignUpAdminRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/auth/register/admin`, signUpAdminRequest, options);
};

/**
 * Refreshes JWT token based on provided refresh token
 * @summary Refresh token
 */
export const refresh = <TData = AxiosResponse<JwtResponse>>(
  refreshBody: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/auth/refresh`, refreshBody, options);
};

/**
 * Authenticates user based on provided credentials and generates JWT token
 * @summary User login
 */
export const login = <TData = AxiosResponse<JwtResponse>>(
  signInRequest: SignInRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/auth/login`, signInRequest, options);
};

/**
 * Retrieves user information by their ID
 * @summary Get user by ID
 */
export const getUserById = <TData = AxiosResponse<GetUserResponse>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/users/${id}`, options);
};

/**
 * Retrieves information about the current user based on the email stored in the JWT payload
 * @summary Get current user
 */
export const getCurrentUser = <TData = AxiosResponse<GetUserResponse>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/users/me`, options);
};

export const getAllUsersBySchemeId = <TData = AxiosResponse<GetUsersPermissionsResponse[]>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/schemes/${id}/users`, options);
};

export type GetSchemeByIdResult = AxiosResponse<SchemeResponse>;
export type UpdateSchemeResult = AxiosResponse<string>;
export type SetPermissionsByIdSchemeResult = AxiosResponse<string>;
export type DeletePermissionsByIdSchemeResult = AxiosResponse<string>;
export type GetAllSchemesResult = AxiosResponse<SchemeResponse[]>;
export type CreateNewSchemeResult = AxiosResponse<SchemeResponse>;
export type RegisterResult = AxiosResponse<JwtResponse>;
export type RegisterAdminResult = AxiosResponse<JwtResponse>;
export type RefreshResult = AxiosResponse<JwtResponse>;
export type LoginResult = AxiosResponse<JwtResponse>;
export type GetUserByIdResult = AxiosResponse<GetUserResponse>;
export type GetCurrentUserResult = AxiosResponse<GetUserResponse>;
export type GetAllUsersBySchemeIdResult = AxiosResponse<GetUsersPermissionsResponse[]>;
