/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Physics circuits simulation Engine
 * Sample API of the Physics project engine
 * OpenAPI spec version: 1.0.0
 */
/**
 * Response for getting user details
 */
export interface GetUserResponse {
  /** User email */
  readonly email?: string;
  /** User ID */
  readonly id?: number;
  /** User name */
  readonly name?: string;
}

export interface SignInRequest {
  email: string;
  password: string;
}

export interface SignUpAdminRequest {
  adminKey: string;
  email: string;
  name: string;
  password: string;
}

/**
 * Error message model
 */
export interface ErrorMessage {
  description?: string;
  message?: string;
  statusCode?: number;
  timestamp?: string;
}

/**
 * JWT Response
 */
export interface JwtResponse {
  /** Access token */
  accessToken: string;
  /** User ID */
  id: number;
  /** User name */
  name: string;
  /** Refresh token */
  refreshToken: string;
  /** Username */
  username: string;
}

export interface SignUpRequest {
  email: string;
  name: string;
  password: string;
}
