spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    name: ${POSTGRES_DB}
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
security:
  jwt:
    secret: ${securityJwtSecret}
    access: ${securityJwtAccess}
    refresh: ${securityJwtRefresh}
  admin:
    data:
      key: ${adminDataKey}
      adminUsername: ${adminUsername}
      adminPassword: ${adminPassword}
      adminName: ${adminName}