name: 'Frontend'
on: 
  pull_request: 
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '21.7.x'
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Lint
      run: pnpm run lint
    - name: Test
      run: pnpm run test --coverage
    - name: 'Report Coverage'
      # Set if: always() to also generate the report if tests are failing
      # Only works if you set `reportOnFailure: true` in your vite config as specified above
      if: always() 
      uses:  davelosert/vitest-coverage-report-action@v2
      with:
        working-directory: ./frontend
  build:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '21.7.x'
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Build
      run: pnpm run build
  docker:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Docker Login
        run: docker login ${{ secrets.REGISTRY_URI }} -u ${{ secrets.REGISTRY_KEYID }} -p ${{ secrets.REGISTRY_KEY_SECRET }}
      - name: Build Docker Image
        run: docker build --tag ${{ secrets.REGISTRY_URI }}/frontend:${{ github.sha }} .
      - name: Push Docker Image to Registry
        run: docker push ${{ secrets.REGISTRY_URI  }}/frontend:${{ github.sha }}
