name: 'Frontend Linters & Tests'
on: 
  pull_request: 

jobs:
  test:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '21.7.x'
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Lint
      run: pnpm run lint
    - name: Test
      run: pnpm run test --coverage
    - name: 'Report Coverage'
      # Set if: always() to also generate the report if tests are failing
      # Only works if you set `reportOnFailure: true` in your vite config as specified above
      if: always() 
      uses:  davelosert/vitest-coverage-report-action@v2
      working-directory: ./frontend
